net: owrt sync, 2016.10

diff --git a/net/irssi/patches/500-autogen.sh.patch b/net/irssi/patches/500-autogen.sh.patch
--- a/net/irssi/patches/500-autogen.sh.patch
+++ b/net/irssi/patches/500-autogen.sh.patch
@@ -1,15 +1,26 @@
 --- a/autogen.sh
 +++ b/autogen.sh
-@@ -25,23 +25,7 @@
+@@ -17,7 +17,7 @@
+ perl syntax.pl
+ 
+ echo "Creating ChangeLog..."
+-git log > $srcdir/ChangeLog
++touch $srcdir/ChangeLog
+ if test "$?" -ne 0; then
+     echo "**Error**: ${PKG_NAME} Autogen must be run in a git clone, cannot proceed."
+     exit 1
+@@ -29,25 +29,7 @@
  files=`echo $files|sed 's/\.in//g'`
  cat docs/help/Makefile.am.gen|sed "s/@HELPFILES@/$files/g"|sed 's/?/\\?/g'|tr '!?' '\t\n' > docs/help/Makefile.am
  
 -# .html -> .txt with lynx or elinks
 -echo "Documentation: html -> txt..."
 -if type lynx >/dev/null 2>&1 ; then
--  lynx -dump -nolist docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
+-  LC_ALL=en_IE.utf8 lynx -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
 -elif type elinks >/dev/null 2>&1 ; then
 -  elinks -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
+-elif type links >/dev/null 2>&1 ; then
+-  links -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
 -else
 -  echo "**Error**: No lynx or elinks present"
 -  exit 1
@@ -25,7 +36,7 @@
  
  rm -f aclocal.m4
  echo "Running autoreconf ..."
-@@ -49,13 +33,5 @@
+@@ -55,13 +37,5 @@
  
  conf_flags="--enable-maintainer-mode"
  
